(function(){
    "use strict";
    
    angular.module('attendance')
    .constant('english', {
        "0": "0",
        "1": "1",
        "2": "2",
        "3": "3",
        "4": "4",
        "5": "5",
        "6": "6",
        "7": "7",
        "8": "8",
        "9": "9",
        ":": ":",
        "/": "/",
        ",": ",",
        ".": ".",
        "D": "D",
        "L": "L",
        "EN": "EN",
        "BN": "BN",
        "AGS_TEXTILES_LIMITED": "AGS Textiles Limited",
        "AGS_TEXTILES_ADDRESS": "Bashir Plaza, Bamoil Bazar, Sarulia Demra, Dhaka-1361 Dhaka, Bangladesh",
        "HOME": "Home",
        "TOTAL_SALARY": "Total Salary",
        "MANAGEMENT": "Management",
        "ADMIN_STAFF": "Admin Staff",
        "PRODUCTION_STAFF": "Production Staff",
        "SEWING_OPERATOR": "Sewing Operator",
        "SEWING_HELPER": "Sewing Helper",
        "CUTTING": "Cutting",
        "QUALITY": "Quality",
        "FINISHING": "Finishing",
        "LOADER_CLEANER": "Loader Cleaner",
        "ENGLISH": "English",
        "BENGALI": "Bengali",
        "EN": "EN",
        "BN": "BN",
        "DARK": "Dark",
        "LIGHT": "Light",
        "SETTINGS": "Settings",
        "ATTENDANCE": "Attendance",
        "BRANCH": "Branch",
        "MONTH": "Month",
        "JANUARY": "January",
        "FEBRUARY": "February",
        "MARCH": "March",
        "APRIL": "April",
        "MAY": "May",
        "JUNE": "June",
        "JULY": "July",
        "AUGUST": "August",
        "SEPTEMBER": "September",
        "OCTOBER": "October",
        "NOVEMBER": "November",
        "DECEMBER": "December",
        "MONTH": "Month",
        "PRINT": "Print",
        "DATE": "Date",
        "YEAR": "Year",
        "MONEY": "Money",
        "DISTRIBUTION": "Distribution",
        "MONEY_DISTRIBUTION_SHEET": "Money Distribution Sheet",
        "MONEY_DISTRIBUTION": "Money Distribution",
        "WORKER_NO": "Worker No",
        "CARD_NO": "Card No",
        "NAME": "Name",
        "GRADE": "Grade",
        "JOINING": "Joining",
        "JOINING_DATE": "Joining Date",
        "ASSIGNED": "Assigned",
        "ATTENDANCE": "Attendance",
        "OVERTIME_HOURS": "Overtime Hours",
        "EXTENDED_HOLIDAYS": "Extended Holdays",
        "HOLIDAY": "Holiday",
        "DISTRIBUTION_TYPE": "Distribution Type",
        "OVERTIME_MONEY": "Overtime Money",
        "HAJIRA_BONUS": "Hajira Bonus",
        "TOTAL_DISTRIBUTED": "Total Distributed",
        "CUT_OUT": "Cut Out",
        "MONEY_RECEIVED": "Money Received",
        "SIGNATURE": "Signature",
        "PRESENT": "Present",
        "ABSENT": "Absent",
        "OTHERS": "Others",
        "DAYS" : "Days",
        "MAIN_SALARY": "Main Salary",
        "HOME_RENT": "Home Rent",
        "MEDICAL_COST": "Medical Cost",
        "TRANSPORT_COST": "Transport Cost",
        "FOOD": "Food",
        "COST": "Cost",
        "OTHER_COMPANY_FACILITIES": "Other Company Facilities",
        "TOTAL_SALARY": "Total Salary",
        "ADVANCED_OTHERS": "Advanced/Others",
        "REVENUE": "Revenue",
        "TOTAL": "Total",
        "SL_NO": "SL. No:",
        "SECTION": "Section",
        "PAYABLE": "Payable",
        "OVERTIME": "Overtime",
        "ATTENDANCE_BONUS": "Attendance Bonus",
        "TOTAL_HOURS": "Total Hours",
        "TOTAL_PERSONS": "Total Persons",
        "TRANSLATE": "Translate",
        "THEME": "Theme",
        "EXPORT": "Export",
        "GUIDE_TOUR": "Guide Tour",
    });
})();